using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ACadInspector.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class CadMetadataGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sourceProvider = context.CompilationProvider.Select((compilation, _) => Generate(compilation));
        context.RegisterSourceOutput(sourceProvider, static (spc, source) =>
        {
            spc.AddSource("CadMetadataRegistry.g.cs", source);
        });
    }

    private static string Generate(Compilation compilation)
    {
        var cadObject = compilation.GetTypeByMetadataName("ACadSharp.CadObject");
        if (cadObject is null)
        {
            return GenerateEmpty();
        }

        var dxfCodeAttr = compilation.GetTypeByMetadataName("ACadSharp.Attributes.DxfCodeValueAttribute");
        var dxfRefType = compilation.GetTypeByMetadataName("ACadSharp.DxfReferenceType");
        var cadSystemVariableAttr = compilation.GetTypeByMetadataName("ACadSharp.Attributes.CadSystemVariableAttribute");

        var allTypes = new List<INamedTypeSymbol>();
        foreach (var asm in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            CollectTypes(asm.GlobalNamespace, allTypes);
        }

        var cadTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

        foreach (var type in allTypes)
        {
            if (type.IsAbstract || type.TypeParameters.Length > 0 || type.IsValueType)
            {
                continue;
            }

            if (!IsPublicApiType(type))
            {
                continue;
            }

            if (IsInExcludedNamespace(type))
            {
                continue;
            }

            if (InheritsFrom(type, cadObject) ||
                HasMetadataAttributes(type, dxfCodeAttr, cadSystemVariableAttr) ||
                IsCadDomainType(type))
            {
                cadTypes.Add(type);
            }
        }

        AddExtraType(compilation, allTypes, cadTypes, "ACadSharp.CadDocument");
        AddExtraType(compilation, allTypes, cadTypes, "ACadSharp.CadSummaryInfo");
        AddExtraType(compilation, allTypes, cadTypes, "ACadSharp.Header.CadHeader");
        AddExtraType(compilation, allTypes, cadTypes, "ACadSharp.Classes.DxfClass");
        AddExtraType(compilation, allTypes, cadTypes, "ACadSharp.Classes.DxfClassCollection");

        var orderedTypes = cadTypes
            .OrderBy(t => t.ToDisplayString())
            .ToArray();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("namespace ACadInspector.Core");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class CadMetadataRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        static partial void Build()");
        sb.AppendLine("        {");
        sb.AppendLine("            TypesInternal.Clear();");

        foreach (var type in orderedTypes)
        {
            var properties = type.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public)
                .Where(p => !p.IsStatic)
                .Where(p => p.GetMethod is not null)
                .Where(p => !p.IsIndexer)
                .Where(p => IsSupportedPropertyType(p.Type, compilation))
                .OrderBy(p => p.Name)
                .ToArray();

            sb.AppendLine($"            TypesInternal.Add(typeof({type.ToDisplayString()}), new CadTypeDescriptor(typeof({type.ToDisplayString()}), new CadPropertyDescriptor[]");
            sb.AppendLine("            {");

            foreach (var prop in properties)
            {
                var canWrite = prop.SetMethod is not null && prop.SetMethod.DeclaredAccessibility == Accessibility.Public;
                var (codes, referenceType) = GetDxfMetadata(prop, dxfCodeAttr, dxfRefType);

                sb.Append("                new CadPropertyDescriptor(");
                sb.Append($"\"{prop.Name}\",");
                sb.Append($" typeof({prop.Type.ToDisplayString()}),");
                sb.Append($" {canWrite.ToString().ToLowerInvariant()},");

                if (codes.Length == 0)
                {
                    sb.Append(" Array.Empty<int>(),");
                }
                else
                {
                    sb.Append(" new int[] { ");
                    sb.Append(string.Join(", ", codes));
                    sb.Append(" },");
                }

                if (referenceType is null)
                {
                    sb.Append(" null,");
                }
                else
                {
                    sb.Append($" \"{referenceType}\",");
                }

                sb.Append($" static instance => (({type.ToDisplayString()})instance).{prop.Name},");

                if (canWrite)
                {
                    sb.AppendLine($" static (instance, value) => (({type.ToDisplayString()})instance).{prop.Name} = ({prop.Type.ToDisplayString()})value!),");
                }
                else
                {
                    sb.AppendLine(" null),");
                }
            }

            sb.AppendLine("            }));");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static (int[] Codes, string? ReferenceType) GetDxfMetadata(
        IPropertySymbol property,
        INamedTypeSymbol? dxfCodeAttr,
        INamedTypeSymbol? dxfReferenceType)
    {
        if (dxfCodeAttr is null)
        {
            return (Array.Empty<int>(), null);
        }

        foreach (var attr in property.GetAttributes())
        {
            if (!SymbolEqualityComparer.Default.Equals(attr.AttributeClass, dxfCodeAttr))
            {
                continue;
            }

            string? referenceType = null;
            var args = attr.ConstructorArguments;
            var argIndex = 0;

            if (args.Length > 0 && args[0].Type is not null && dxfReferenceType is not null &&
                SymbolEqualityComparer.Default.Equals(args[0].Type, dxfReferenceType))
            {
                referenceType = args[0].Value?.ToString();
                argIndex = 1;
            }

            var codes = Array.Empty<int>();
            if (args.Length > argIndex)
            {
                var codesArg = args[argIndex];
                if (codesArg.Kind == TypedConstantKind.Array)
                {
                    codes = codesArg.Values
                        .Where(v => v.Value is not null)
                        .Select(v => (int)v.Value!)
                        .ToArray();
                }
                else if (codesArg.Value is int i)
                {
                    codes = new[] { i };
                }
            }

            return (codes, referenceType);
        }

        return (Array.Empty<int>(), null);
    }

    private static bool InheritsFrom(INamedTypeSymbol type, INamedTypeSymbol baseType)
    {
        var current = type.BaseType;
        while (current is not null)
        {
            if (SymbolEqualityComparer.Default.Equals(current, baseType))
            {
                return true;
            }
            current = current.BaseType;
        }

        return false;
    }

    private static bool HasMetadataAttributes(
        INamedTypeSymbol type,
        INamedTypeSymbol? dxfCodeAttr,
        INamedTypeSymbol? cadSystemVariableAttr)
    {
        if (dxfCodeAttr is null && cadSystemVariableAttr is null)
        {
            return false;
        }

        foreach (var prop in type.GetMembers().OfType<IPropertySymbol>())
        {
            if (prop.DeclaredAccessibility != Accessibility.Public || prop.IsStatic)
            {
                continue;
            }

            foreach (var attr in prop.GetAttributes())
            {
                if (dxfCodeAttr is not null &&
                    SymbolEqualityComparer.Default.Equals(attr.AttributeClass, dxfCodeAttr))
                {
                    return true;
                }

                if (cadSystemVariableAttr is not null &&
                    SymbolEqualityComparer.Default.Equals(attr.AttributeClass, cadSystemVariableAttr))
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static bool IsCadDomainType(INamedTypeSymbol type)
    {
        var nsValue = type.ContainingNamespace?.ToDisplayString();
        if (string.IsNullOrWhiteSpace(nsValue))
        {
            return false;
        }

        var ns = nsValue!;
        if (!ns.StartsWith("ACadSharp", StringComparison.Ordinal))
        {
            return false;
        }

        if (ns.StartsWith("ACadSharp.IO", StringComparison.Ordinal))
        {
            return false;
        }

        return true;
    }

    private static bool IsInExcludedNamespace(INamedTypeSymbol type)
    {
        var ns = type.ContainingNamespace?.ToDisplayString();
        return ns is not null &&
               ns.StartsWith("ACadSharp.IO", StringComparison.Ordinal);
    }

    private static bool IsPublicApiType(INamedTypeSymbol type)
    {
        if (type.DeclaredAccessibility != Accessibility.Public)
        {
            return false;
        }

        for (var current = type.ContainingType; current is not null; current = current.ContainingType)
        {
            if (current.DeclaredAccessibility != Accessibility.Public)
            {
                return false;
            }
        }

        return true;
    }

    private static void CollectTypes(INamespaceSymbol ns, List<INamedTypeSymbol> results)
    {
        foreach (var type in ns.GetTypeMembers())
        {
            results.Add(type);
            CollectNested(type, results);
        }

        foreach (var child in ns.GetNamespaceMembers())
        {
            CollectTypes(child, results);
        }
    }

    private static void CollectNested(INamedTypeSymbol type, List<INamedTypeSymbol> results)
    {
        foreach (var nested in type.GetTypeMembers())
        {
            results.Add(nested);
            CollectNested(nested, results);
        }
    }

    private static string GenerateEmpty()
    {
        return "// <auto-generated />\n" +
               "namespace ACadInspector.Core\n" +
               "{\n" +
               "    public static partial class CadMetadataRegistry\n" +
               "    {\n" +
               "        static partial void Build() { }\n" +
               "    }\n" +
               "}\n";
    }

    private static void AddExtraType(
        Compilation compilation,
        List<INamedTypeSymbol> allTypes,
        HashSet<INamedTypeSymbol> target,
        string metadataName)
    {
        var type = ResolveTypeByMetadataName(compilation, allTypes, metadataName);

        if (type is null)
        {
            return;
        }

        if (type.IsAbstract || type.TypeParameters.Length > 0 || type.IsValueType)
        {
            return;
        }

        if (type.DeclaredAccessibility != Accessibility.Public &&
            !(type.DeclaredAccessibility == Accessibility.Internal &&
              SymbolEqualityComparer.Default.Equals(type.ContainingAssembly, compilation.Assembly)))
        {
            return;
        }

        target.Add(type);
    }

    private static INamedTypeSymbol? ResolveTypeByMetadataName(
        Compilation compilation,
        List<INamedTypeSymbol> allTypes,
        string metadataName)
    {
        var type = compilation.GetTypeByMetadataName(metadataName);
        if (type is not null)
        {
            return type;
        }

        var lastDot = metadataName.LastIndexOf('.');
        if (lastDot <= 0 || lastDot == metadataName.Length - 1)
        {
            return allTypes.FirstOrDefault(t => string.Equals(t.Name, metadataName, StringComparison.Ordinal));
        }

        var ns = metadataName.Substring(0, lastDot);
        var name = metadataName.Substring(lastDot + 1);
        return allTypes.FirstOrDefault(t =>
            string.Equals(t.Name, name, StringComparison.Ordinal) &&
            string.Equals(t.ContainingNamespace?.ToDisplayString(), ns, StringComparison.Ordinal));
    }

    private static bool IsSupportedPropertyType(ITypeSymbol type, Compilation compilation)
    {
        if (!IsAccessibleType(type, compilation))
        {
            return false;
        }

        return !ContainsTypeParameters(type);
    }

    private static bool ContainsTypeParameters(ITypeSymbol type)
    {
        if (type.TypeKind == TypeKind.TypeParameter)
        {
            return true;
        }

        if (type is IArrayTypeSymbol array)
        {
            return ContainsTypeParameters(array.ElementType);
        }

        if (type is INamedTypeSymbol named)
        {
            if (named.IsUnboundGenericType || named.TypeParameters.Length > 0)
            {
                return true;
            }

            foreach (var arg in named.TypeArguments)
            {
                if (ContainsTypeParameters(arg))
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static bool IsAccessibleType(ITypeSymbol type, Compilation compilation)
    {
        if (!compilation.IsSymbolAccessibleWithin(type, compilation.Assembly))
        {
            return false;
        }

        if (type is IArrayTypeSymbol array)
        {
            return IsAccessibleType(array.ElementType, compilation);
        }

        if (type is INamedTypeSymbol named)
        {
            if (named.DeclaredAccessibility != Accessibility.Public)
            {
                return false;
            }

            for (var current = named.ContainingType; current is not null; current = current.ContainingType)
            {
                if (current.DeclaredAccessibility != Accessibility.Public)
                {
                    return false;
                }
            }

            foreach (var arg in named.TypeArguments)
            {
                if (!IsAccessibleType(arg, compilation))
                {
                    return false;
                }
            }
        }

        return true;
    }
}
