using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ProCad.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class CadHeaderMetadataGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sourceProvider = context.CompilationProvider.Select((compilation, _) => Generate(compilation));
        context.RegisterSourceOutput(sourceProvider, static (spc, source) =>
        {
            spc.AddSource("CadHeaderMetadataRegistry.g.cs", source);
        });
    }

    private static string Generate(Compilation compilation)
    {
        var headerType = compilation.GetTypeByMetadataName("ACadSharp.Header.CadHeader");
        var attributeType = compilation.GetTypeByMetadataName("ACadSharp.Attributes.CadSystemVariableAttribute");
        var dxfReferenceType = compilation.GetTypeByMetadataName("ACadSharp.DxfReferenceType");

        if (headerType is null || attributeType is null)
        {
            return GenerateEmpty();
        }

        var items = new List<SystemVariableItem>();
        foreach (var prop in headerType.GetMembers().OfType<IPropertySymbol>())
        {
            if (prop.DeclaredAccessibility != Accessibility.Public || prop.IsStatic || prop.GetMethod is null || prop.IsIndexer)
            {
                continue;
            }

            if (!TryGetSystemVariableData(prop, attributeType, dxfReferenceType, out var data))
            {
                continue;
            }

            items.Add(new SystemVariableItem(prop, data));
        }

        var ordered = items
            .OrderBy(item => item.Data.VariableName, StringComparer.Ordinal)
            .ThenBy(item => item.Property.Name, StringComparer.Ordinal)
            .ToArray();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using ACadSharp.Header;");
        sb.AppendLine("namespace ProCad.Core");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class CadHeaderMetadataRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        static partial void Build()");
        sb.AppendLine("        {");
        sb.AppendLine("            VariablesInternal.Clear();");

        foreach (var item in ordered)
        {
            var prop = item.Property;
            var data = item.Data;
            var canWrite = prop.SetMethod is not null && prop.SetMethod.DeclaredAccessibility == Accessibility.Public;
            var typeName = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sb.Append("            VariablesInternal.Add(new CadHeaderVariableDescriptor(");
            sb.Append(FormatString(data.VariableName));
            sb.Append(", ");
            sb.Append(FormatString(prop.Name));
            sb.Append(", typeof(");
            sb.Append(typeName);
            sb.Append("), ");
            sb.Append(canWrite ? "true" : "false");
            sb.Append(", ");
            sb.Append(FormatCodes(data.Codes));
            sb.Append(", ");
            sb.Append(FormatNullableString(data.ReferenceType));
            sb.Append(", ");
            sb.Append(data.IsName ? "true" : "false");
            sb.Append(", ");
            sb.Append("static header => header.");
            sb.Append(prop.Name);
            sb.Append(", ");
            if (canWrite)
            {
                sb.Append("static (header, value) => header.");
                sb.Append(prop.Name);
                sb.Append(" = (");
                sb.Append(typeName);
                sb.Append(")value!");
            }
            else
            {
                sb.Append("null");
            }
            sb.AppendLine("));");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static bool TryGetSystemVariableData(
        IPropertySymbol property,
        INamedTypeSymbol attributeType,
        INamedTypeSymbol? dxfReferenceType,
        out SystemVariableData data)
    {
        foreach (var attr in property.GetAttributes())
        {
            if (!SymbolEqualityComparer.Default.Equals(attr.AttributeClass, attributeType))
            {
                continue;
            }

            var args = attr.ConstructorArguments;
            var index = 0;
            string? referenceType = null;
            var isName = false;

            if (args.Length > 0 && args[0].Type is not null && dxfReferenceType is not null &&
                SymbolEqualityComparer.Default.Equals(args[0].Type, dxfReferenceType))
            {
                referenceType = args[0].Value?.ToString();
                index++;
            }

            string? variableName = null;
            if (index < args.Length && args[index].Value is string variable)
            {
                variableName = variable;
                index++;
            }

            if (index < args.Length && args[index].Type?.SpecialType == SpecialType.System_Boolean)
            {
                if (args[index].Value is bool flag)
                {
                    isName = flag;
                }
                index++;
            }

            var codes = new List<int>();
            for (var i = index; i < args.Length; i++)
            {
                AppendCodes(args[i], codes);
            }

            data = new SystemVariableData(
                variableName ?? property.Name,
                codes.Count == 0 ? Array.Empty<int>() : codes.ToArray(),
                isName,
                referenceType);
            return true;
        }

        data = default;
        return false;
    }

    private static void AppendCodes(TypedConstant constant, List<int> codes)
    {
        if (constant.Kind == TypedConstantKind.Array)
        {
            foreach (var value in constant.Values)
            {
                AppendCodes(value, codes);
            }
            return;
        }

        if (constant.Value is null)
        {
            return;
        }

        if (constant.Type?.TypeKind == TypeKind.Enum)
        {
            codes.Add(Convert.ToInt32(constant.Value, CultureInfo.InvariantCulture));
            return;
        }

        switch (constant.Value)
        {
            case int i:
                codes.Add(i);
                break;
            case short s:
                codes.Add(s);
                break;
            case byte b:
                codes.Add(b);
                break;
            case long l:
                codes.Add((int)l);
                break;
        }
    }

    private static string FormatCodes(int[] codes)
    {
        if (codes.Length == 0)
        {
            return "Array.Empty<int>()";
        }

        return "new int[] { " + string.Join(", ", codes) + " }";
    }

    private static string FormatString(string value)
    {
        return "\"" + Escape(value) + "\"";
    }

    private static string FormatNullableString(string? value)
    {
        return value is null ? "null" : FormatString(value);
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string GenerateEmpty()
    {
        return "// <auto-generated />\n" +
               "namespace ProCad.Core\n" +
               "{\n" +
               "    public static partial class CadHeaderMetadataRegistry\n" +
               "    {\n" +
               "        static partial void Build() { }\n" +
               "    }\n" +
               "}\n";
    }

    private readonly struct SystemVariableItem
    {
        public SystemVariableItem(IPropertySymbol property, SystemVariableData data)
        {
            Property = property;
            Data = data;
        }

        public IPropertySymbol Property { get; }
        public SystemVariableData Data { get; }
    }

    private readonly struct SystemVariableData
    {
        public SystemVariableData(string variableName, int[] codes, bool isName, string? referenceType)
        {
            VariableName = variableName;
            Codes = codes;
            IsName = isName;
            ReferenceType = referenceType;
        }

        public string VariableName { get; }
        public int[] Codes { get; }
        public bool IsName { get; }
        public string? ReferenceType { get; }
    }
}
